layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

navigation:
  - title: About Me
    url: /index.html
  - title: Projects
    url: /projects
  - title: My Thoughts
    url: /thoughts

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: sourab-pareek-2401a788
  # mastodon: your_username
  medium: sourabiit
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: OpenFAAS
    web_url: https://github.com/openfaas/faas
    image_url: https://raw.githubusercontent.com/openfaas/openfaas.github.io/master/images/openfaas/logo.png

  - name: Kubernetes
    web_url: https://www.kubernetes.io
    image_url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
